### ISSUE TITLE
arrange_schedule died because expire_data_check(t) error

### ISSUE THREAD

**Issue by icecat2012** [SWLBot/electronic-blackboard#158]
from commit b383168378237d2aca4a208b1e3534ab63121585
PLEASE ALWAYS DONE TEST RUN BEFORE PUSH

Traceback (most recent call last):
  File "arrange_schedule.py", line 1717, in <module>
    main()
  File "arrange_schedule.py", line 1504, in main
    alarm_expire_data_check,shutdown = expire_data_check(raw_time)
  File "arrange_schedule.py", line 1435, in expire_data_check
    return alarm_expire_data_check,shutdown
UnboundLocalError: local variable 'shutdown' referenced before assignment

**Comment by Billy4195** [comment]
Sorry, that's my fault.
I have push a patch on #159 .
